### 1. 채팅메시지 생성 API
POST http://localhost:8080/v1/chat
Content-Type: application/json

{
  "content": "채팅메시지 생성 테스트2",
  "senderId": "1",
  "roomId": "1"
}

### 2. 채팅 메시지 조회 API
GET http://localhost:8080/v1/chat/list/1

